name: Build

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0

      - name: Install dependencies
        working-directory: ./app/dashboard
        run: npm ci

      - name: Build project
        working-directory: ./app/dashboard
        run: VITE_BASE_API=/api/ npm run build --if-present -- --outDir build --assetsDir statics

      - name: Create 404.html
        working-directory: ./app/dashboard
        run: cp ./build/index.html ./build/404.html

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lower-repo
        id: lower-repo
        run: |
          echo "IMAGE=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.ref_name }}-build-cache 
          cache-to: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ github.ref_name }}-build-cache,mode=max
          tags: |
            turbotaxmachine/marzban:latest
            turbotaxmachine/marzban:${{github.ref_name}}
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
            ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{github.ref_name}}
